services:
  pytorch_container:
    image: rocm/pytorch:latest
    container_name: pytorch_container1
    stdin_open: true
    tty: true
    shm_size: 20G
    privileged: true
    devices:
      - "/dev/kfd"
      - "/dev/dri"
    group_add:
      - video
    ipc: host
    ports:
      - "2022:22"
    volumes:
      - .:/workspace
    command: bash -c "
      apt-get update && apt-get install -y openssh-server && \
      echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config && \
      echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config && \
      echo 'root:Test123!' | chpasswd && \
      mkdir -p /var/run/sshd && \
      pip install albumentations timm torchmetrics && \
      service ssh start && bash"
