name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "dev" ]


permissions:
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run tests with pytest and check coverage
        run: |
          pytest --cov=backend/src --cov-fail-under=70 --cov-report=xml:coverage/coverage.xml
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
      - name: Build Sphinx documentation
        run: |
          cd docs
          sphinx-apidoc -o source/_modules ../backend/src
          make html
      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation-artifact
          path: docs/build/html

